// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "GoADS Middleware",
            "url": "https://github.com/yourusername/goadstc"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/structs/{name}/fields": {
            "post": {
                "description": "Write multiple fields to a struct using byte offset method",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "structs"
                ],
                "summary": "Write struct fields",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"MAIN.myStruct\"",
                        "description": "Struct symbol name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to write",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/middleware.WriteStructFieldsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/middleware.WriteStructFieldsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/symbols/{name}/value": {
            "post": {
                "description": "Write a value to a PLC symbol with automatic type encoding",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "symbols"
                ],
                "summary": "Write symbol value",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"MAIN.temperature\"",
                        "description": "Symbol name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Value to write",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/middleware.WriteSymbolRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/middleware.WriteSymbolResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/control": {
            "post": {
                "description": "Execute PLC control commands (start, stop, reset)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "control"
                ],
                "summary": "Control PLC",
                "parameters": [
                    {
                        "description": "Control command",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/middleware.ControlRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/middleware.ControlResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check if the server and PLC connection are healthy",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/middleware.HealthResponse"
                        }
                    }
                }
            }
        },
        "/info": {
            "get": {
                "description": "Get server and PLC connection information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Server info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/middleware.InfoResponse"
                        }
                    }
                }
            }
        },
        "/state": {
            "get": {
                "description": "Retrieve current PLC state (running, stopped, etc.)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "control"
                ],
                "summary": "Get PLC state",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/middleware.StateResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/structs/{name}": {
            "get": {
                "description": "Read an entire struct with all its fields",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "structs"
                ],
                "summary": "Read struct",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"MAIN.myStruct\"",
                        "description": "Struct symbol name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/middleware.SymbolValueResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/symbols": {
            "get": {
                "description": "Retrieve all symbols from the PLC symbol table",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "symbols"
                ],
                "summary": "Get symbol table",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/middleware.SymbolTableResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/symbols/read": {
            "post": {
                "description": "Read multiple symbol values in a single request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "symbols"
                ],
                "summary": "Batch read symbols",
                "parameters": [
                    {
                        "description": "List of symbols to read",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/middleware.BatchReadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/middleware.BatchReadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/symbols/write": {
            "post": {
                "description": "Write multiple symbol values in a single request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "symbols"
                ],
                "summary": "Batch write symbols",
                "parameters": [
                    {
                        "description": "Map of symbols to values",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/middleware.BatchWriteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/middleware.BatchWriteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/symbols/{name}": {
            "get": {
                "description": "Retrieve metadata for a specific symbol",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "symbols"
                ],
                "summary": "Get symbol metadata",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"MAIN.temperature\"",
                        "description": "Symbol name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/middleware.SymbolInfo"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/symbols/{name}/value": {
            "get": {
                "description": "Read the current value of a PLC symbol with automatic type detection",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "symbols"
                ],
                "summary": "Read symbol value",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"MAIN.temperature\"",
                        "description": "Symbol name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/middleware.SymbolValueResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "description": "Retrieve PLC runtime name and version information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Get runtime version",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/middleware.VersionResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ws/subscribe": {
            "get": {
                "description": "Establish WebSocket connection for real-time symbol value updates",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "websocket"
                ],
                "summary": "WebSocket subscription endpoint",
                "responses": {
                    "101": {
                        "description": "Switching Protocols",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "middleware.BatchReadRequest": {
            "type": "object",
            "properties": {
                "symbols": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "MAIN.temperature",
                        "MAIN.counter"
                    ]
                }
            }
        },
        "middleware.BatchReadResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "additionalProperties": true
                },
                "errors": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "middleware.BatchWriteRequest": {
            "type": "object"
        },
        "middleware.BatchWriteResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "results": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "boolean"
                    }
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "middleware.ControlRequest": {
            "type": "object",
            "properties": {
                "command": {
                    "description": "\"start\", \"stop\", \"reset\"",
                    "type": "string"
                }
            }
        },
        "middleware.ControlResponse": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "middleware.ErrorDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "object",
                    "additionalProperties": true
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "middleware.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/middleware.ErrorDetail"
                }
            }
        },
        "middleware.HealthResponse": {
            "type": "object",
            "properties": {
                "connected": {
                    "type": "boolean"
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "middleware.InfoResponse": {
            "type": "object",
            "properties": {
                "ams_net_id": {
                    "type": "string"
                },
                "ams_port": {
                    "type": "integer"
                },
                "connected": {
                    "type": "boolean"
                },
                "server_uptime": {
                    "type": "string"
                },
                "source_net_id": {
                    "type": "string"
                },
                "symbol_count": {
                    "type": "integer"
                },
                "target": {
                    "type": "string"
                }
            }
        },
        "middleware.StateResponse": {
            "type": "object",
            "properties": {
                "ads_state": {
                    "type": "integer"
                },
                "ads_state_name": {
                    "type": "string"
                },
                "device_state": {
                    "type": "integer"
                },
                "error": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "middleware.SymbolInfo": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "index_group": {
                    "type": "integer"
                },
                "index_offset": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "middleware.SymbolTableResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "error": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "symbols": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/middleware.SymbolInfo"
                    }
                }
            }
        },
        "middleware.SymbolValueResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "symbol": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "value": {}
            }
        },
        "middleware.VersionResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "major_version": {
                    "type": "integer"
                },
                "minor_version": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "version": {
                    "type": "string"
                },
                "version_build": {
                    "type": "integer"
                }
            }
        },
        "middleware.WriteStructFieldsRequest": {
            "type": "object"
        },
        "middleware.WriteStructFieldsResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "fields_written": {
                    "type": "integer"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "middleware.WriteSymbolRequest": {
            "type": "object"
        },
        "middleware.WriteSymbolResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "symbol": {
                    "type": "string"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Symbol read/write operations",
            "name": "symbols"
        },
        {
            "description": "Struct field manipulation",
            "name": "structs"
        },
        {
            "description": "Health and info endpoints",
            "name": "health"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "GoADS HTTP/WebSocket Middleware API",
	Description:      "REST API for interacting with TwinCAT PLC via ADS protocol\n\n## Features\n- Read and write PLC symbols with automatic type detection\n- Batch operations for multiple symbols\n- Struct field manipulation using byte offsets\n- Symbol table retrieval with metadata\n- WebSocket streaming for real-time symbol notifications (coming soon)",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
